services:
  fire-monitoring-bot:
    build: .
    container_name: active-fire-bot
    environment:
      - FIRE_BOT_DATA_DIR=/app/data
      - MONGO_URI=mongodb://username:password@your-mongodb-host:27017/
      - MONGO_DB_NAME=fire_monitoring
      - MONGO_COLLECTION_NAME=detected_fires
    volumes:
      - ./data:/app/data
    restart: unless-stopped
